import 'package:flutter/material.dart';
import 'package:town_seek/models/business.dart';
import 'package:town_seek/models/product.dart';
import 'package:town_seek/models/service.dart';
import 'package:town_seek/models/booking.dart';
import 'package:town_seek/models/booking_status.dart';
import 'package:town_seek/services/supabase_service.dart';
import 'package:town_seek/widgets/shop_tag.dart';
import 'package:town_seek/models/review.dart';
import 'package:town_seek/data/wishlist_manager.dart';
import 'package:town_seek/utils/ui_utils.dart';
import 'package:town_seek/screens/main/main_screen.dart';

class ShopPage extends StatefulWidget {
  final Business business;

  const ShopPage({
    super.key,
    required this.business,
  });

  @override
  State<ShopPage> createState() => _ShopPageState();
}

class _ShopPageState extends State<ShopPage> with TickerProviderStateMixin {
  late TabController _tabController;
  List<Product> _products = [];
  List<Service> _services = [];
  List<Review> _reviews = [];
  bool _isLoading = true;
  bool _isWishlisted = false;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 3, vsync: this);
    _isWishlisted = WishlistManager().isWishlisted(widget.business.id);
    _fetchData();
  }

  Future<void> _fetchData() async {
    setState(() => _isLoading = true);
    try {
      final products = await SupabaseService.getProducts(widget.business.id);
      final services = await SupabaseService.getServices(widget.business.id);
      final reviews = await SupabaseService.getBusinessReviews(widget.business.id);
      setState(() {
        _products = products;
        _services = services;
        _reviews = reviews;
        _isLoading = false;
      });
    } catch (e) {
      setState(() => _isLoading = false);
      if (mounted) {
        UIUtils.showPopup(context, 'Error loading data: $e', isError: true);
      }
    }
  }

  Future<void> _handleBooking(Service service) async {
    final user = SupabaseService.currentUser;
    if (user == null) {
      if (context.mounted) {
        UIUtils.showPopup(context, 'Please login to book a service', isError: true);
      }
      return;
    }

    try {
      final booking = Booking(
        id: '', // Will be generated by Supabase
        userId: user.id,
        businessId: widget.business.id,
        serviceId: service.id,
        status: BookingStatus.pending,
        bookingDate: DateTime.now().add(const Duration(days: 1)), // Sample: Book for tomorrow
        createdAt: DateTime.now(),
      );

      await SupabaseService.createBooking(booking);
      if (mounted) {
        UIUtils.showPopup(context, 'Booking request sent successfully!');
      }
    } catch (e) {
      if (mounted) {
        UIUtils.showPopup(context, 'Booking failed: $e', isError: true);
      }
    }
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white,
      body: NestedScrollView(
        headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
          return <Widget>[
            SliverAppBar(
              expandedHeight: 250.0,
              pinned: true,
              backgroundColor: const Color(0xFF2962FF),
              flexibleSpace: FlexibleSpaceBar(
                background: widget.business.imageUrl != null 
                  ? Image.network(widget.business.imageUrl!, fit: BoxFit.cover)
                  : Container(color: Colors.blue[100], child: const Icon(Icons.store, size: 80, color: Colors.blue)),
              ),
              leading: IconButton(
                icon: const Icon(Icons.arrow_back, color: Colors.white),
                onPressed: () => Navigator.pop(context),
              ),
              actions: [
                IconButton(
                  icon: Icon(
                    _isWishlisted ? Icons.favorite : Icons.favorite_border,
                    color: _isWishlisted ? Colors.red : Colors.white,
                  ),
                  onPressed: () {
                    setState(() {
                      _isWishlisted = !_isWishlisted;
                    });
                    WishlistManager().toggleWishlist(widget.business);
                    if (context.mounted) {
                      UIUtils.showPopup(context, _isWishlisted ? 'Added to Wishlist' : 'Removed from Wishlist');
                    }
                  },
                ),
              ],
            ),
            SliverToBoxAdapter(
              child: Padding(
                padding: const EdgeInsets.all(20),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceBetween,
                      children: [
                        Expanded(
                          child: Text(
                            widget.business.name,
                            style: const TextStyle(fontSize: 24, fontWeight: FontWeight.bold),
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 12),
                    Row(
                      mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                      children: [
                        _ActionButton(icon: Icons.call, label: 'Call', color: Colors.green, onTap: () {}),
                        _ActionButton(icon: Icons.directions, label: 'Route', color: Colors.blue, onTap: () {}),
                        _ActionButton(icon: Icons.chat, label: 'Chat', color: Colors.orange, onTap: () {}),
                      ],
                    ),
                    const SizedBox(height: 16),
                    const SizedBox(height: 8),
                    Text(widget.business.category ?? 'Local Business', style: TextStyle(color: Colors.grey[600], fontSize: 16)),
                    const SizedBox(height: 12),
                    if (widget.business.address != null)
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: [
                          Row(
                            children: [
                              const Icon(Icons.location_on, color: Colors.blue, size: 18),
                              const SizedBox(width: 8),
                              Expanded(child: Text(widget.business.address!)),
                            ],
                          ),
                          if (widget.business.latitude != null && widget.business.longitude != null)
                            TextButton.icon(
                              onPressed: () {
                                // Go to Explore tab and center on this business
                                final mainScreen = context.findAncestorStateOfType<MainScreenState>();
                                if (mainScreen != null) {
                                  mainScreen.goToTab(1);
                                  // Map centering logic will naturally happen as markers are loaded
                                  // but we can pass coords via a static or global state if needed.
                                  // For now, simple tab switch is good.
                                }
                              },
                              icon: const Icon(Icons.map, size: 16),
                              label: const Text('View on Map'),
                              style: TextButton.styleFrom(
                                padding: EdgeInsets.zero,
                                visualDensity: VisualDensity.compact,
                              ),
                            ),
                        ],
                      ),
                    const SizedBox(height: 12),
                    Wrap(
                      spacing: 8,
                      runSpacing: 8,
                      children: widget.business.tags.map((t) => ShopTag(text: t)).toList(),
                    ),
                  ],
                ),
              ),
            ),
            SliverPersistentHeader(
              pinned: true,
              delegate: _SliverAppBarDelegate(
                TabBar(
                  controller: _tabController,
                  labelColor: const Color(0xFF2962FF),
                  unselectedLabelColor: Colors.grey,
                  indicatorColor: const Color(0xFF2962FF),
                  tabs: const [
                    Tab(text: "Products"),
                    Tab(text: "Offers"),
                    Tab(text: "Reviews"),
                  ],
                ),
              ),
            ),
          ];
        },
        body: _isLoading 
          ? const Center(child: CircularProgressIndicator())
          : TabBarView(
              controller: _tabController,
              children: [
                _buildProductsTab(),
                _buildServicesTab(),
                _buildReviewsTab(),
              ],
            ),
      ),
    );
  }

  Widget _buildProductsTab() {
    if (_products.isEmpty) return const Center(child: Text("No products found"));
    return GridView.builder(
      padding: const EdgeInsets.all(15),
      gridDelegate: const SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 2,
        mainAxisSpacing: 15,
        crossAxisSpacing: 15,
        childAspectRatio: 0.7,
      ),
      itemCount: _products.length,
      itemBuilder: (context, index) {
        final product = _products[index];
        return Card(
          elevation: 2,
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              Expanded(
                child: ClipRRect(
                  borderRadius: const BorderRadius.vertical(top: Radius.circular(15)),
                  child: product.imageUrl != null 
                    ? Image.network(product.imageUrl!, fit: BoxFit.cover, width: double.infinity)
                    : Container(color: Colors.grey[200], child: const Icon(Icons.image)),
                ),
              ),
              Padding(
                padding: const EdgeInsets.all(10),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(product.name, style: const TextStyle(fontWeight: FontWeight.bold), maxLines: 1),
                    Text('Rs ${product.price}', style: const TextStyle(color: Colors.blue, fontWeight: FontWeight.bold)),
                    const SizedBox(height: 4),
                    SizedBox(
                      width: double.infinity,
                      child: ElevatedButton(
                        style: ElevatedButton.styleFrom(
                          backgroundColor: Colors.blue,
                          padding: EdgeInsets.zero,
                          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(8)),
                        ),
                        onPressed: () {
                          UIUtils.showPopup(context, '${product.name} added to cart');
                        },
                        child: const Text('Add', style: TextStyle(color: Colors.white, fontSize: 12)),
                      ),
                    ),
                  ],
                ),
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildServicesTab() {
    if (_services.isEmpty) return const Center(child: Text("No services found"));
    return ListView.builder(
      padding: const EdgeInsets.all(15),
      itemCount: _services.length,
      itemBuilder: (context, index) {
        final service = _services[index];
        return Card(
          margin: const EdgeInsets.only(bottom: 12),
          shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
          child: ListTile(
            contentPadding: const EdgeInsets.all(10),
            leading: ClipRRect(
              borderRadius: BorderRadius.circular(10),
              child: service.imageUrl != null 
                ? Image.network(service.imageUrl!, width: 60, height: 60, fit: BoxFit.cover)
                : Container(width: 60, height: 60, color: Colors.grey[200]),
            ),
            title: Text(service.name, style: const TextStyle(fontWeight: FontWeight.bold)),
            subtitle: Text('Rs ${service.price} (${service.durationMinutes} mins)'),
            trailing: ElevatedButton(
              style: ElevatedButton.styleFrom(backgroundColor: Colors.green),
              onPressed: () => _handleBooking(service),
              child: const Text('Book', style: TextStyle(color: Colors.white)),
            ),
          ),
        );
      },
    );
  }

  Widget _buildReviewsTab() {
    return Column(
      children: [
        Padding(
          padding: const EdgeInsets.all(15),
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              const Text("Customer Reviews", style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold)),
              TextButton.icon(
                icon: const Icon(Icons.edit, size: 18),
                label: const Text("Write a review"),
                onPressed: _showReviewDialog,
              ),
            ],
          ),
        ),
        Expanded(
          child: _reviews.isEmpty
              ? const Center(child: Text("No reviews yet"))
              : ListView.builder(
                  padding: const EdgeInsets.symmetric(horizontal: 15),
                  itemCount: _reviews.length,
                  itemBuilder: (context, index) {
                    final review = _reviews[index];
                    return Card(
                      margin: const EdgeInsets.only(bottom: 12),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12)),
                      child: Padding(
                        padding: const EdgeInsets.all(12),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              children: [
                                CircleAvatar(
                                  radius: 18,
                                  backgroundImage: review.userAvatar != null ? NetworkImage(review.userAvatar!) : null,
                                  child: review.userAvatar == null ? const Icon(Icons.person, size: 20) : null,
                                ),
                                const SizedBox(width: 10),
                                Expanded(
                                  child: Column(
                                    crossAxisAlignment: CrossAxisAlignment.start,
                                    children: [
                                      Text(review.userName ?? "Anonymous", style: const TextStyle(fontWeight: FontWeight.bold)),
                                      Row(
                                        children: List.generate(5, (i) => Icon(
                                          Icons.star,
                                          size: 14,
                                          color: i < review.rating ? Colors.amber : Colors.grey[300],
                                        )),
                                      ),
                                    ],
                                  ),
                                ),
                                Text(
                                  "${review.createdAt.day}/${review.createdAt.month}/${review.createdAt.year}",
                                  style: TextStyle(color: Colors.grey[600], fontSize: 12),
                                ),
                              ],
                            ),
                            if (review.comment != null && review.comment!.isNotEmpty) ...[
                              const SizedBox(height: 10),
                              Text(review.comment!),
                            ],
                          ],
                        ),
                      ),
                    );
                  },
                ),
        ),
      ],
    );
  }

  void _showReviewDialog() {
    final user = SupabaseService.currentUser;
    if (user == null) {
      UIUtils.showPopup(context, 'Please login to write a review', isError: true);
      return;
    }

    int rating = 5;
    final commentController = TextEditingController();

    showDialog(
      context: context,
      builder: (context) => StatefulBuilder(
        builder: (context, setDialogState) => AlertDialog(
          title: const Text("Write a Review"),
          content: Column(
            mainAxisSize: MainAxisSize.min,
            children: [
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: List.generate(5, (index) => IconButton(
                  icon: Icon(
                    index < rating ? Icons.star : Icons.star_border,
                    color: Colors.amber,
                  ),
                  onPressed: () => setDialogState(() => rating = index + 1),
                )),
              ),
              TextField(
                controller: commentController,
                decoration: const InputDecoration(hintText: "Your comment (optional)"),
                maxLines: 3,
              ),
            ],
          ),
          actions: [
            TextButton(onPressed: () => Navigator.pop(context), child: const Text("Cancel")),
            ElevatedButton(
              onPressed: () async {
                final review = Review(
                  id: '', 
                  userId: user.id,
                  businessId: widget.business.id,
                  rating: rating,
                  comment: commentController.text.trim(),
                  createdAt: DateTime.now(),
                );
                 try {
                   await SupabaseService.addReview(review);
                   if (context.mounted) {
                     Navigator.pop(context);
                     _fetchData(); // Refresh reviews
                   }
                 } catch (e) {
                   if (context.mounted) {
                     UIUtils.showPopup(context, 'Error: $e', isError: true);
                   }
                 }
              },
              child: const Text("Submit"),
            ),
          ],
        ),
      ),
    );
  }
}

class _ActionButton extends StatelessWidget {
  final IconData icon;
  final String label;
  final Color color;
  final VoidCallback onTap;

  const _ActionButton({required this.icon, required this.label, required this.color, required this.onTap});

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      child: Column(
        children: [
          CircleAvatar(
            backgroundColor: color.withValues(alpha: 0.1),
            child: Icon(icon, color: color),
          ),
          const SizedBox(height: 4),
          Text(label, style: TextStyle(color: color, fontWeight: FontWeight.bold, fontSize: 12)),
        ],
      ),
    );
  }
}

class _SliverAppBarDelegate extends SliverPersistentHeaderDelegate {
  final TabBar _tabBar;
  _SliverAppBarDelegate(this._tabBar);
  @override 
  double get minExtent => _tabBar.preferredSize.height;
  @override 
  double get maxExtent => _tabBar.preferredSize.height;
  @override
  Widget build(BuildContext context, double shrinkOffset, bool overlapsContent) {
    return Container(color: Colors.white, child: _tabBar);
  }
  @override 
  bool shouldRebuild(_SliverAppBarDelegate oldDelegate) => false;
}
